from graphics import *
from time import sleep
def main() :
    win = GraphWin("My Clock", 1000, 1000)
    win.setBackground("blue")
    a = Circle(Point(500,500), 300)
    a.setFill("white")
    a.setOutline("black")
    a.setWidth(20)
    a.draw(win)
    c = Polygon(Point(496,500),Point(504,500),Point(500,240))
    c.setFill("black")
    c.draw(win)
    d = Polygon(Point(504,490),Point(496,510),Point(675,625))
    d.setFill("black")
    d.draw(win)
    b = Circle(Point(500,500), 20)
    b.setFill("gray")
    b.setOutline("black")
    b.setWidth(2)
    b.draw(win)
    t = Text(Point(500,225),"12")
    t.setSize(25)
    t.draw(win)
    ti = Text(Point(500,775),"6")
    ti.setSize(25)
    ti.draw(win)
    tim = Text(Point(775,500),"3")
    tim.setSize(25)
    tim.draw(win)
    time = Text(Point(225,500),"9")
    time.setSize(25)
    time.draw(win)
    e = Line(Point(560,480),Point(250,600))
    e.setFill("red")
    e.draw(win)
    sleep(.5)
    win.setBackground("red")
    e.undraw()
    sleep(.5)
    win.setBackground("white")
    b.undraw()
    e = Line(Point(550,495),Point(250,500))
    e.setFill("red")
    e.draw(win)
    b.draw(win)
    sleep(.5)
    win.setBackground("black")
    e.undraw()
    sleep(.5)
    win.setBackground("blue")
    b.undraw()
    e = Line(Point(540,510),Point(250,400))
    e.setFill("red")
    e.draw(win)
    b.draw(win)
    sleep(.5)
    win.setBackground("red")
    e.undraw()
    sleep(.5)
    win.setBackground("white")
    b.undraw()
    e = Line(Point(530,525),Point(300,320))
    e.setFill("red")
    e.draw(win)
    b.draw(win)
    sleep(.5)
    win.setBackground("black")
    e.undraw()
    sleep(.5)
    win.setBackground("blue")
    b.undraw()
    e = Line(Point(520,540),Point(380,265))
    e.setFill("red")
    e.draw(win)
    b.draw(win)
    sleep(.5)
    win.setBackground("red")
    e.undraw()
    sleep(.5)
    win.setBackground("white")
    b.undraw()
    e = Line(Point(500,565),Point(500,240))
    e.setFill("red")
    e.draw(win)
    b.draw(win)
    z = Text(Point(500,150),"The Time")
    z.setFill("gray")
    z.setSize(36)
    z.draw(win)
    win.getMouse() # pause for click in window
    win.close()
main()